#! /bin/sh

chosen=$(printf "Power Off\nRestart\nLock" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
    "Power Off") poweroff ;;
    "Restart") reboot ;;
    "Lock") sh -c '(sleep 0.5s; hyprlock)' & disown ;;
    *) exit 1 ;;
esac
